@startuml
abstract class Matematica {
    + {static} GerarPtosCirculo(angulo:double, raio:double) : Ponto4D
    + {static} GerarPtosCirculoSimetrico(raio:double) : double
    + {static} Dentro(bBox:BBox, pto:Ponto4D) : bool
    + {static} distanciaQuadrado(ptoA:Ponto4D, ptoB:Ponto4D) : double
    + {static} distancia(ptoA:Ponto4D, ptoB:Ponto4D) : double
    + {static} ScanLineInterseccao(yi:double, y1:double, y2:double) : double
    + {static} ScanLineCalculaXi(x1:double, x2:double, ti:double) : double
    + {static} ScanLine(ptoClique:Ponto4D, ptoIni:Ponto4D, ptoFim:Ponto4D) : bool
}
@enduml
